name: Sync Fork with Upstream

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: main # Assuming 'main' is your default branch

      - name: Setup Git
        run: |
          git config --global user.email "benjaminshawki@gmail.com"
          git config --global user.name "benjaminshawki"

      - name: Sync fork
        run: |
          git remote add upstream https://github.com/zootedb0t/citruszest.nvim.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
